before_install:
        - sudo apt-get install -y cmake libgtkmm-3.0-dev libglibmm-2.4-dev libtorrent-rasterbar-dev libboost-dev
language: cpp
compiler:
        - gcc
        - clang

# Change this to your needs
script: mkdir -p build && cd build/ && cmake .. && make
